"""
app.py
The main Flask application exposing the Drug Discovery API.
Contains a POST endpoint that uses our heuristic generator and RDKit analyzer.
Optionally integrates with an Ollama API for text generation.
"""

from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
from generator import generate_molecules
from analyzer import analyze_molecule
import requests

app = Flask(__name__)
# Enable CORS so our frontend can communicate with the backend seamlessly
CORS(app)

# ==============================================================================
# OLLAMA API INTEGRATION (OPTIONAL)
# ==============================================================================
def get_ollama_comment(target, smiles):
    """
    Attempts to call a local Ollama instance to get a chemical expert comment on the molecule.
    If Ollama is not running, it gracefully catches the error and returns a generic message.
    """
    ollama_url = "http://localhost:11434/api/generate"
    prompt = f"Act as an expert medicinal chemist. I have generated a candidate molecule for {target} with SMILES '{smiles}'. Write a very brief, one-sentence comment on its potential chemical properties or why it might be suitable as a generic inhibitor scaffold. Do not use markdown."
    
    payload = {
        "model": "phi3",
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(ollama_url, json=payload, timeout=5)
        response.raise_for_status()
        data = response.json()
        return data.get("response", "No response generated by AI.")
    except requests.exceptions.RequestException as e:
        return "Ollama currently unavailable. Please start the local Ollama server to get AI comments."

# ==============================================================================
# API ENDPOINTS
# ==============================================================================

@app.route("/")
def index():
    """
    Serves the main frontend page.
    """
    return render_template("index.html")

@app.route("/generate", methods=["POST"])
def generate_endpoint():
    """
    Endpoint that handles the generation and analysis workflow.
    Expects JSON body: { "target": "Cancer" }
    """
    data = request.get_json()
    if not data or "target" not in data:
        return jsonify({"error": "Missing 'target' in request body."}), 400
        
    target = data.get("target")
    
    try:
        candidate_smiles = generate_molecules(target, num_molecules=10)
    except Exception as e:
        return jsonify({"error": f"Error during generation: {str(e)}"}), 500

    results = []
    for smiles in candidate_smiles:
        analysis = analyze_molecule(smiles)
        if analysis["valid"]:
            results.append({
                "smiles": smiles,
                "score": analysis["score"],
                "properties": analysis["properties"]
            })
            
    results.sort(key=lambda x: x["score"], reverse=True)
    top_results = results[:5]
    
    if len(top_results) > 0:
        best_smiles = top_results[0]["smiles"]
        ai_comment = get_ollama_comment(target, best_smiles)
        top_results[0]["ai_comment"] = ai_comment

    return jsonify({
        "molecules": top_results
    }), 200

# ==============================================================================
# MAIN ENTRY POINT
# ==============================================================================
if __name__ == "__main__":
    app.run(debug=True, host="127.0.0.1", port=5000)

